Resources:
  WindLoadingLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData: 
        EbsOptimized: false
        KeyName: awsoregon
        UserData:
          Fn::Base64:
            !Sub
            - |
                MIME-Version: 1.0
                Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="

                --==MYBOUNDARY==
                Content-Type: text/cloud-config; charset="us-ascii"
                
                runcmd:
                  - amazon-linux-extras install -y lustre2.10
                  - mkdir -p /fsx
                  - mount -t lustre -o defaults,_netdev,flock,user_xattr,noatime ${fsx_id}.fsx.us-west-2.amazonaws.com@tcp:/${mount_name} /fsx 
                  
                --==MYBOUNDARY==--
            - fsx_id: "fs-0e6759f50ff7a310c"
              mount_name: "x346hbmv"
      LaunchTemplateName: WindLoadingTemplate  
  WindLoadingCompute:
    Type: AWS::Batch::ComputeEnvironment
    Properties: 
      ComputeEnvironmentName: WindLoadingCompute
      ComputeResources: 
        AllocationStrategy: BEST_FIT
        DesiredvCpus: 32
        Ec2KeyPair: awsoregon
        InstanceRole: arn:aws:iam::378722409401:instance-profile/ecsInstanceRole
        InstanceTypes:
          - optimal
        LaunchTemplate:
          LaunchTemplateId: !Ref WindLoadingLaunchTemplate
          Version: $Default
        MaxvCpus: 2000
        MinvCpus: 0
        SecurityGroupIds:
          - sg-b3f854c8
        Subnets:
          - subnet-7979c31c
        Type: EC2
      ServiceRole: arn:aws:iam::378722409401:role/service-role/AWSBatchServiceRole
      State: ENABLED
      Type: MANAGED
  WindLoadingJobQueue:
    Type: AWS::Batch::JobQueue
    Properties: 
      ComputeEnvironmentOrder: 
        - ComputeEnvironment: !Ref WindLoadingCompute
          Order: 1
      Priority: 1
      JobQueueName: WindLoadingJobQueue
      State: ENABLED
  WindLoadingJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties: 
      ContainerProperties: 
        Command:
          - ./windloading
        Environment:
          - Name: FEM_REPO
            Value: /fsx/20220308_1335_MT_mount_zen_30_m1HFN_FSM/
          - Name: M1CALIBRATION
            Value: /fsx/m1calibration/
        Image: 378722409401.dkr.ecr.us-west-2.amazonaws.com/gmto.im/windloading:latest
        ResourceRequirements:
          - Type: VCPU
            Value: '32'
          - Type: MEMORY
            Value: '10000'
        MountPoints:
          - ContainerPath: /fsx
            SourceVolume: fsx
        Volumes:
          - Host:
              SourcePath: /fsx
            Name: fsx        
      JobDefinitionName: WindLoadingJob
      PlatformCapabilities: 
        - EC2
      Type: container
